export enum DinteroStatus {
    INITIALIZED = "INITIALIZED",
    ON_HOLD = "ON_HOLD",
    AUTHORIZED = "AUTHORIZED",
    PARTIALLY_CAPTURED = "PARTIALLY_CAPTURED",
    CAPTURED = "CAPTURED",
    AUTHORIZATION_VOIDED = "AUTHORIZATION_VOIDED",
    PARTIALLY_REFUNDED = "PARTIALLY_REFUNDED",
    REFUNDED = "REFUNDED",
    REJECTED = "REJECTED",
    FAILED = "FAILED",
}
